# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py
# This file is licensed under the Apache License v2.0 with LLVM Exceptions.
# See https://llvm.org/LICENSE.txt for license information.
# SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
#
# (c) Copyright 2025-2026 Advanced Micro Devices, Inc. or its affiliates

# RUN: llc -mtriple=aie2p -run-pass=postmisched --aie-postpipeliner-vreg-mode %s -o - | FileCheck %s

# This test verifies that the --aie-postpipeliner-vreg-mode option correctly
# replaces filtered physical registers with virtual registers of the appropriate class.

---
name:            simple_scalar_def_use
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: simple_scalar_def_use
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $lc = MOV_alu_mv_mv_mv_scl $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $p6, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $r0 = MOV_alu_mv_mv_mv_scl $p6
  ; CHECK-NEXT:   renamable $r1 = ADD_NC_mv_add_rr killed renamable $r0, renamable $r2
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0.entry:
    liveins: $p0
    successors: %bb.1
    $lc = MOV_alu_mv_mv_mv_scl $p0

  bb.1:
    successors: %bb.1, %bb.2
    liveins: $p0, $p6, $r2

    renamable $r0 = MOV_alu_mv_mv_mv_scl $p6
    renamable $r1 = ADD_NC_mv_add_rr renamable $r0, renamable $r2
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1

  bb.2:
    RET implicit $lr
    DelayedSchedBarrier

...
---
name:            composite_dm_register
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: composite_dm_register
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $lc = MOV_alu_mv_mv_mv_scl $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $p1, $y5, $y0, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dm4 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y renamable $y5, renamable $y0, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   VST_CONV_bf16_fp32_dmx_sts_srs_bf_idx_imm killed renamable $cml4, renamable $p0, 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
  ; CHECK-NEXT:   VST_CONV_bf16_fp32_dmx_sts_srs_bf_idx_imm killed renamable $cmh4, renamable $p1, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0.entry:
    liveins: $p0
    successors: %bb.1
    $lc = MOV_alu_mv_mv_mv_scl $p0

  bb.1:
    successors: %bb.1, %bb.2
    liveins: $p0, $p1, $y5, $y0, $r2

    renamable $dm4 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y renamable $y5, renamable $y0, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask

    VST_CONV_bf16_fp32_dmx_sts_srs_bf_idx_imm renamable $cml4, renamable $p0, 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    VST_CONV_bf16_fp32_dmx_sts_srs_bf_idx_imm renamable $cmh4, renamable $p1, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd

    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1

  bb.2:
    RET implicit $lr
    DelayedSchedBarrier

...
---
name:            partial_composite_def
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: partial_composite_def
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $cmh4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $lc = MOV_alu_mv_mv_mv_scl $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $p7, $cmh4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $cml4 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_idx_imm renamable $p7, 0 :: (load (<32 x s16>))
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   renamable $ex2 = VCONV_bfp16ebs8_fp32 renamable $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0.entry:
    liveins: $p0, $cmh4
    successors: %bb.1
    $lc = MOV_alu_mv_mv_mv_scl $p0

  bb.1:
    successors: %bb.1, %bb.2
    liveins: $p0, $p7, $cmh4

    renamable $cml4 = VLDA_CONV_fp32_bf16_dmx_lda_ups_bf_idx_imm renamable $p7, 0 :: (load (<32 x s16>))

    renamable $ex2 = VCONV_bfp16ebs8_fp32 renamable $dm4, implicit-def $srf2bflags, implicit $crf2bmask, implicit $crrnd

    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1

  bb.2:
    RET implicit $lr
    DelayedSchedBarrier

...
---
name:            tied_operands
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: tied_operands
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0, $p3, $d0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $lc = MOV_alu_mv_mv_mv_scl $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $p3, $d0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   dead $r1, $p3, $dc0 = LDA_2D_dms_lda killed $p3, $d0 :: (load (s32))
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0.entry:
    liveins: $p0, $p3, $d0
    successors: %bb.1
    $lc = MOV_alu_mv_mv_mv_scl $p0

  bb.1:
    successors: %bb.1, %bb.2
    liveins: $p0, $p3, $d0

    dead $r1, $p3, $dc0 = LDA_2D_dms_lda $p3, $d0 :: (load (s32))
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1

  bb.2:
    RET implicit $lr
    DelayedSchedBarrier

...
---
name:            composite_with_liveout
tracksRegLiveness: true
body:             |
  ; CHECK-LABEL: name: composite_with_liveout
  ; CHECK: bb.0.entry:
  ; CHECK-NEXT:   successors: %bb.1(0x80000000)
  ; CHECK-NEXT:   liveins: $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   $lc = MOV_alu_mv_mv_mv_scl $p0
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   successors: %bb.1(0x40000000), %bb.2(0x40000000)
  ; CHECK-NEXT:   liveins: $p0, $y5, $y0, $r2
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   renamable $dm4 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y renamable $y5, renamable $y0, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   VST_CONV_bf16_fp32_dmx_sts_srs_bf_idx_imm killed renamable $cml4, renamable $p0, 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
  ; CHECK-NEXT:   PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.2:
  ; CHECK-NEXT:   liveins: $p0, $cmh4
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT:   RET implicit $lr
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   VST_CONV_bf16_fp32_dmx_sts_srs_bf_idx_imm killed renamable $cmh4, killed renamable $p0, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
  ; CHECK-NEXT:   NOP
  ; CHECK-NEXT:   DelayedSchedBarrier
  bb.0.entry:
    liveins: $p0
    successors: %bb.1
    $lc = MOV_alu_mv_mv_mv_scl $p0

  bb.1:
    successors: %bb.1, %bb.2
    liveins: $p0, $y5, $y0, $r2

    renamable $dm4 = VMUL_f_vmul_bf_vmul_bf_core_Y_Y renamable $y5, renamable $y0, renamable $r2, implicit-def dead $srfpflags, implicit $crfpmask
    VST_CONV_bf16_fp32_dmx_sts_srs_bf_idx_imm renamable $cml4, renamable $p0, 0, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    PseudoLoopEnd <mcsymbol .L_LEnd0>, %bb.1

  bb.2:
    liveins: $p0, $cmh4
    VST_CONV_bf16_fp32_dmx_sts_srs_bf_idx_imm renamable $cmh4, renamable $p0, 64, implicit-def $srf2fflags, implicit $crf2fmask, implicit $crrnd
    RET implicit $lr
    DelayedSchedBarrier

...
